/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Divider: typeof import('./components/Divider/index.vue')['default']
    HomeGrid: typeof import('./components/HomeGrid/index.vue')['default']
    HomeNoticeBar: typeof import('./components/HomeNoticeBar/index.vue')['default']
    HomeSwipe: typeof import('./components/HomeSwipe/index.vue')['default']
    HomeTeamName: typeof import('./components/HomeTeamName/index.vue')['default']
    RotatingVerification: typeof import('./components/RotatingVerification/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanDivider: typeof import('vant/es')['Divider']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
